project/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

project/letters/urls.py
from django.urls import path

from . import views

app_name = "letters"
urlpatterns = [
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("create/<int:pk>/", views.create, name="create"),
    path("mailbox/", views.mailbox, name="mailbox"),
    path("drafts/", views.drafts, name="drafts")
]

project/projects/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('letters/', include('letters.urls', namespace='letters',)),
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% tailwind_css %}
  </head>

  <body
    class="bg-spring_green-400 font-serif leading-normal tracking-wide flex flex-col min-h-screen"
  >

    <!-- navbar -->
    <nav
      class="w-full flex relative justify-between items-center mx-auto px-8 h-10 text-yellow-100"
    >
      <div class="inline-flex">
        <a class="inline-block py-2 px-3 rounded-sm" href="/">
          <div
            class="flex items-center relative cursor-pointer whitespace-nowrap"
          >
            kanka
          </div>
        </a>
      </div>
      <div class="inline-flex">
        {% if user.is_authenticated %}
        <a class="inline-block py-2 px-3 rounded-sm" href="/letters/mailbox/"
        >mailbox</a
        >
        <a class="inline-block py-2 px-3 rounded-sm" href="/accounts/profile/"
          >profile</a
        >
        <a class="inline-block py-2 px-3 rounded-sm" href="/accounts/logout/"
          >logout</a
        >
        {% else %}
        <a class="inline-block py-2 px-3 rounded-sm" href="/accounts/login/"
          >login</a
        >
        {% endif %}
      </div>
    </nav>
    <!-- end of navbar -->


    <main class="w-full flex-grow">
      <!-- {% if messages %}
      <div class="space-y-4 text-center">
        {% for message in messages %}
        <div
          class="{% if message.tags %} alert inline-block text-xs p-1 text-white
          {% if message.tags == 'error' %}bg-rose-600{% elif message.tags == 'info' %}bg-blue-500{% else %}bg-green-500{% endif %}{% endif %}"
        >
          {{ message }}
        </div>
        {% endfor %}
      </div>
      {% endif %} -->

      {% block content %}
      {% endblock content %}
    </main>

    <footer class="py-2">
      <div class="container mx-auto text-center">
        <p class="text-yellow-100 font-extralight text-xs">
          &copy; huse kivrak
        </p>
      </div>
    </footer>
  </body>
</html>

project/theme/templates/index.html
{% extends 'base.html' %}
{% block title %}kanka{% endblock %}


{% block content %}
<div class="w-full md:max-w-2xl mx-auto text-center">
  {% if user.is_authenticated %} {% if messages %} {% for message in messages %}
  <h1 class="text-chartreuse-100 mb-4">{{ message }}</h1>
  {% endfor %} {% endif %}

  <div class="w-full md:max-w-2xl mx-auto text-center">
    <a
      class="inline-block py-2 px-3 text-chartreuse-200 hover:text-chartreuse-100 rounded-sm"
      href="/letters/create/"
      >write a letter</a
    >
    <a
      class="inline-block py-2 px-3 text-chartreuse-200 hover:text-chartreuse-100 rounded-sm"
      href="/letters/drafts/"
      >drafts</a
    >
  </div>
  {% else %}

  <!-- unauthorized homepage: -->

  <h1 class="text-white mb-0 tracking-widest text-4xl">
    welcome to kanka
  </h1>
  <h2 class="text-chartreuse-50 mb-4 text-lg">
    modern letter correspondence
  </h2>

  <div class="mb-10">
    <h3 class="text-chartreuse-100">
      send and recieve custom letters in real-time
      <br/>

    </h3>
      <ul class="mt-2 text-sm">
        <li class="text-chartreuse-100"> • fully customizable letters</li>
        <li class="text-chartreuse-100"> • accurate delivery times</li>
        <li class="text-chartreuse-100"> • snail mail stuff</li>
      </ul>
  </div>

  <div class="mb-10">
    <a
    class="inline-block text-chartreuse-100 hover:text-chartreuse-50 text-lg"
    href="/accounts/register/"
    >sign up</a
    >
  </div>


  <p class="text-chartreuse-100 text-sm">already a member?</p>
  <a
  class="inline-block py-1 px-3 text-lg text-chartreuse-100 hover:text-chartreuse-50"
  href="/accounts/login/"
  >login here</a
  >

  <div class="mt-6">
    <h3 id="" class="text-chartreuse-50 text-md tracking-widest">...what's a "kanka"?</h3>
    <span class="text-chartreuse-100 text-xs">
      just Turkish slang for a close friend!
    </span>

  </div>
  {% endif %}
</div>
{% endblock %}

project/theme/templates/letter_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}write a letter{% endblock title %}

{% block content %}
<div class="w-full md:max-w-2xl mx-auto text-center">
  <form
    method="post"
    action="{% if letter %}/letters/create/{{ letter.pk }}/{% else %}/letters/create/{% endif %}"
    class="flex flex-col items-center"
    >

    {% csrf_token %}
    {{ form.media }}

    <label for="title" class="block mb-2 text-sm font-medium text-white"
      >title:</label
    >

    <input
      type="text"
      name="title"
      placeholder="just for your reference; the recipient won't see it"
      value="{% if letter %}{{ letter.title }}{% endif %}"
      class="text-white text-sm p-2 bg-yellow-300 w-1/2 border border-yellow-100 rounded-lg block placeholder-white"
    />

    {% if form.errors.title %}
    <div class="text-red-600 text-sm italic">{{ form.errors.title }}</div>
    {% endif %}

    <br />

    <label for="body" class="block mb-2 text-sm font-medium text-white"
      >letter:</label
    >
    {{ form.body }}

    {% if form.errors.body %}
    <div class="text-red-600 text-sm italic">{{ form.errors.body }}</div>
    {% endif %}

    <br />

    <select
      name="recipient"
      id="recipient"
      class="text-white text-sm rounded-lg block p-2 mt-0 bg-yellow-200 border-yellow-50 placeholder-chartruese-100"
      required
    >
      <!-- Preselect recipient if editing a draft -->
      {% if letter %}
      <option selected value="{{ letter.recipient.pk }}">
        {{ letter.recipient.username }}
      </option>
      {% else %}
      <option selected disabled value="">choose a recipient</option>
      {% endif %}

      <!-- don't repeat preselected recipient if editing a draft-->
      {% for user in users %}
        {% if not letter or user.pk != letter.recipient.pk %}
        <option value="{{ user.pk }}">{{ user.username }}</option>
        {% endif %}
      {% endfor %}
    </select>

    <br />

    <div class="flex items-center justify-center space-x-10">
      <input
        type="submit"
        name="save_draft_button"
        value="save as draft"
        class="text-white text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 bg-rose-400 border-yellow-50 placeholder-gray-400"
      />

      <input
        type="submit"
        name="send_button"
        value="send"
        class="text-white text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 bg-spring_green-300 border-yellow-50 placeholder-gray-400"
      />

    </div>
  </form>
</div>

{% endblock content %}

project/theme/templates/letter_detail.html
{% extends 'base.html' %} {% block title %}{{letter.title}}{% endblock title %}
{% block content %}
<div class="w-full md:max-w-2xl mx-auto text-center">
  <h1>{{letter.title}}</h1>
  <div class="letter-body">
    <p>{{letter.body | safe }}</p>
  </div>
</div>
  {% endblock content %}

project/theme/templates/letter_drafts.html
{% extends 'base.html' %}
{% block title %}drafts{% endblock %}

{% block content %}
<div class="w-full max-w-2xl mx-auto px-6 py-8 text-center">
  <h1 class="text-2xl text-chartreuse-50 tracking-wider">your drafts</h1>

  {% if not drafts %}
    <p class="text-chartreuse-100 text-sm mt-4">you have no drafts</p>
    <a href="{% url 'letters:create' %}" class="text-chartreuse-100">write one!</a>
  {% else %}
    {% for draft in drafts %}
    <ul class="list-none mt-2 text-white text-sm">
      <li>
        <a href="{% url 'letters:create' pk=draft.id %}" class="text-chartreuse-100">{{ draft.title }}</a>
      </li>
    </ul>
    {% endfor %}
  {% endif %}
</div>
{% endblock %}

project/theme/templates/login.html
{% extends 'base.html' %}
{% block title %}kanka: login{% endblock %}

{% block content %}
<div class="w-full md:max-w-xs mx-auto py-8">
  <form method="post" action="/accounts/login/" class="flex flex-col items-center">
    {% csrf_token %}
    <div class="mb-4 w-full">
      <label
        class="block text-white text-sm font-medium mb-2"
        for="{{ form.username.id_for_label }}"
      >
        username
      </label>
      <input
        name="{{ form.username.name }}"
        class="text-white text-sm p-2 bg-yellow-200 w-full min-w-0 border border-yellow-50 rounded-lg focus:ring-blue-500 focus:border-blue-500 block placeholder-gray-400"
        id="{{ form.username.id_for_label }}"
        type="text"
        placeholder="artemis"
        required
      />
    </div>
    <div class="mb-6 w-full">
      <label
        class="block text-white text-sm font-medium mb-2"
        for="{{ form.password.id_for_label }}"
      >
        password
      </label>
      <input
        name="{{ form.password.name }}"
        class="text-white text-sm p-2 bg-yellow-200 w-full min-w-0 border border-yellow-50 rounded-lg focus:ring-blue-500 focus:border-blue-500 block placeholder-gray-400"
        id="{{ form.password.id_for_label }}"
        type="password"
        placeholder="c@tNip123"
        required
      />
    </div>
    <div class="flex items-center justify-center">
      <button
        class="text-white text-sm bg-chartreuse-200 p-2 rounded-lg hover:bg-chartreuse-100"
        type="submit"
      >
        sign in
      </button>
    </div>
  </form>
</div>
{% endblock content %}

project/theme/templates/mailbox.html
{% extends 'base.html' %}
{% block title %}{{request.user}}'s mailbox{% endblock %}

{% block content %}
<div class="w-full max-w-2xl mx-auto px-6 py-8 text-center">
  <h1 class="text-4xl text-chartreuse-100 font-medium">mailbox</h1>
  {% if mailbox_count %}
  <h2 class="text-2xl text-chartreuse-200 font-light">
    {{mailbox_count}} letters
  </h2>
  {% else %}
  <h2 class="text-2xl text-chartreuse-200 font-light">
    no letters
  </h2>
  {% endif %}
</div>
{% endblock %}

project/theme/templates/profile.html
{% extends 'base.html' %}
{% block title %}{{request.user}}{% endblock title %}

{% block content %}
<!-- <div class="w-full md:max-w-2xl mx-auto text-center">
  <a class="inline-block py-2 px-3 text-chartreuse-200 hover:text-chartreuse-100 rounded-sm" href="/letters/create/">write a letter</a>
  <a class="inline-block py-2 px-3 text-chartreuse-200 hover:text-chartreuse-100 rounded-sm" href="/letters/drafts/">drafts</a>
</div> -->
<p>under construction</p>

{% endblock content %}

project/theme/templates/register.html
{% extends 'base.html' %}
{% block title %}kanka: register{% endblock %}

{% block content %}

<div class="w-full max-w-xs mx-auto py-8">
  <form method="post" action="/accounts/register/">
    {% csrf_token %}
    <div class="mb-4">
      <label for="username" class="block mb-2 text-sm font-medium text-white"
        >username</label
      >
      <input
        type="text"
        name="username"
        id="username"
        class="text-white text-sm p-2 bg-yellow-200 w-full min-w-0 border border-yellow-50 rounded-lg focus:ring-blue-500 focus:border-blue-500 block placeholder-gray-400 mt-0.5"
      />
    </div>

    <div class="mb-4">
      <label for="email" class="block mb-2 text-sm font-medium text-white"
        >email</label
      >
      <input
        type="email"
        name="email"
        id="email"
        class="text-white text-sm p-2 bg-yellow-200 w-full min-w-0 border border-yellow-50 rounded-lg focus:ring-blue-500 focus:border-blue-500 block placeholder-gray-400 mt-0.5"
      />
    </div>

    <div class="mb-4">
      <label for="password" class="block mb-2 text-sm font-medium text-white"
        >password</label
      >
      <input
        type="password"
        name="password1"
        id="password"
        class="text-white text-sm p-2 bg-yellow-200 w-full min-w-0 border border-yellow-50 rounded-lg focus:ring-blue-500 focus:border-blue-500 block placeholder-gray-400 mt-0.5"
      />
    </div>

    <div class="mb-4">
      <label for="password" class="block mb-2 text-sm font-medium text-white"
        >password again</label
      >
      <input
        type="password"
        name="password2"
        id="password"
        class="text-white text-sm p-2 bg-yellow-200 w-full min-w-0 border border-yellow-50 rounded-lg focus:ring-blue-500 focus:border-blue-500 block placeholder-gray-400 mt-0.5"
      />
    </div>

    <div class="mb-4">
      <label for="zip_code" class="block mb-2 text-sm font-medium text-white"
        >zip code</label
      >
      <input
        type="text"
        name="zip_code"
        id="zip_code"
        class="text-white text-sm p-2 bg-yellow-200 w-full min-w-0 border border-yellow-50 rounded-lg focus:ring-blue-500 focus:border-blue-500 block placeholder-gray-400 mt-0.5"
      />
    </div>

    <button
      type="submit"
      class="text-white text-sm mt-6 rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 bg-spring_green-200 border-yellow-50 placeholder-gray-400"
    >
      register
    </button>
  </form>
</div>

{% endblock content%}